### ISSUE TITLE
Usage of @Nullable annotation

### ISSUE THREAD

**Issue by VasileUngureanu** [futurice/freesound-android#110]
Hi,
I use your application as reference.
 
You/We have View Widgets  and Injected dependencies that are annotated with @Nullable.

@Nullable annotation act like in Kotlin "?". It means that we need to write use case to deal with both cases when something can be null or not. In other words its part of business logic.

Lets analyze View Widget:
`
 @Nullable
    @BindView(id.search_view)
    SearchView searchView;
`

If is annotated with @Nullable then probably there are some business logic regarding this widget where in some cases it can be null and in other not. 
The same are with injected dependencies. 
Analyzing the code we see that only case when widgets and dependencies can be null is case when something goes wrong with Butterknife and Dagger but its have nothing related to business logic. 
 
I think that both widgets and dependencies needed to be annotated with @NonNull because there is no use case when they can be null and run specific logic.
 
All these @Nullable annotations make class full of "non null" checks to fix "lint" warnings.

Probably you put @Nullable instead of @NonNull to fix "lint" warning that suggest to initialize the property.

Maybe in case with generated initializations (Butterknife, Dagger ...) we no need to use @NonNull/@Nullable annotations at all.

Thanks for helping me understand!

**Comment by peter-tackage** [comment]
I've also been reconsidering our rather gratuitous use of `@Nullable` because of exactly the reasons you have described - that `@Nullable` should be driven by business/API reasons rather by-product of the lifecycle and/or view binding technicalities.

If I'm not mistaken, Kotlin has `lateinit` and `by lazy` keywords which might do a better job of conveying the idea of what we are really trying to achieve. But we're not using Kotlin, at least not yet.

In any case, I would agree that it would be better if we removed `@Nullable` unless we consider the field to be optional. Any thoughts @tomaszpolanski ?

**Comment by peter-tackage** [comment]
I've made https://github.com/futurice/freesound-android/pull/111 as an experiment

**Comment by tomaszpolanski** [comment]
With ButterKnife bindings I find it tedious to use those nullables. 
As long we make linter happy in some way, I'm fine by skipping those nullables.

**Comment by peter-tackage** [comment]
Resolved via #111
