### ISSUE TITLE
Different user for freesound API

### ISSUE THREAD

**Issue by luciapayo** [futurice/freesound-android#123]
Since I am not in Futurice anymore I created my own clientId and clientSecret. There is a problem though for the "users/{user}/" call, the user is hardcoded in the app to SpiceProgram and I have my own user, so this won't work. If I change it to my user name it works but then I don't see the awesome spice program chillicorn avatar anymore :´´´´´´´(

What should we do?

**Comment by peter-tackage** [comment]
The SpiceProgram user is fetched as a public profile, so it shouldn't matter which user created the clientId/clientSecret combination. In any case, the SpiceProgram user wasn't actually the user that created those credentials - that was a different user. 

Can you recheck and see if it's still a problem? I'm wondering if the problem was caused by #122 or perhaps some issue where you hadn't defined both `freesound.api.clientId` and `freesound.api.clientSecret` - there were some breaking changes that I recently merged, so old freesound-api.properties files would no longer work without modifications.

**Comment by luciapayo** [comment]
You are right, it works fine. 

Closing.
